/*
SQLyog Job Agent Version 8.82 Copyright(c) Webyog Softworks Pvt. Ltd. All Rights Reserved.

MySQL - 5.6.16  
*********************************************************************
*/
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/* SYNC DB : asesores_viejo */ 
SET AUTOCOMMIT = 0;
/* SYNC TABLE : `usu_permisos_menu` */

	/*Start of batch : 1 */
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 717) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 718) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 719) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 720) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 721) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 722) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 723) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 724) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 725) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 878) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 877) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 876) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 875) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 874) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 873) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 872) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 871) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 870) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 869) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 868) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 858) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 857) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 856) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 855) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 854) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 853) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 852) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 851) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 850) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 849) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 848) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 847) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 846) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 845) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 844) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 843) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 842) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 841) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 840) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 839) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 838) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 837) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 836) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 835) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 834) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 833) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 832) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 831) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 830) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 829) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 828) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 827) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 826) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 825) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 824) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 823) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 822) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 821) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 820) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 819) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 818) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 817) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 816) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 815) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 814) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 813) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 812) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 811) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 810) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 809) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 808) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 807) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 806) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 800) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 801) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 802) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 803) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 804) ;
DELETE FROM `asesores_viejo`.`usu_permisos_menu`  WHERE (`id_permiso` = 805) ;
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1008', '1', '6');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1140', '8', '66');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1139', '8', '63');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1138', '8', '60');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1137', '8', '58');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1136', '8', '56');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1135', '8', '55');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('782', '7', '63');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('781', '7', '60');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('780', '7', '59');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('779', '7', '58');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('778', '7', '56');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('777', '7', '55');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('776', '7', '54');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('775', '7', '57');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('774', '7', '45');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('773', '7', '41');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('772', '7', '40');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('771', '7', '12');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('770', '7', '11');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('769', '7', '10');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('768', '7', '64');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('767', '7', '7');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('766', '7', '6');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('765', '7', '62');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('764', '7', '61');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('763', '7', '50');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('762', '7', '47');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('761', '7', '46');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('760', '7', '5');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('759', '7', '2');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('758', '7', '1');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1134', '8', '54');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1133', '8', '29');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1132', '8', '20');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1131', '8', '53');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1130', '8', '57');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1129', '8', '45');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1128', '8', '41');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1127', '8', '40');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1126', '8', '52');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1125', '8', '51');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1124', '8', '49');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1123', '8', '48');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1122', '8', '44');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1121', '8', '43');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1120', '8', '34');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1119', '8', '33');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1118', '8', '31');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1117', '8', '38');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1116', '8', '21');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1115', '8', '17');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1114', '8', '28');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1113', '8', '27');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1112', '8', '19');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1111', '8', '16');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1110', '8', '15');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1109', '8', '14');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1108', '8', '13');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1107', '8', '12');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1106', '8', '11');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1105', '8', '10');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1104', '8', '9');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1103', '8', '8');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1102', '8', '64');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1101', '8', '7');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1100', '8', '6');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1099', '8', '62');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1098', '8', '61');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1097', '8', '47');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1096', '8', '46');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1095', '8', '5');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1094', '8', '3');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('999', '1', '1');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1000', '1', '2');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1001', '1', '3');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1002', '1', '5');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1003', '1', '46');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1004', '1', '47');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1005', '1', '50');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1006', '1', '61');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1007', '1', '62');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1141', '8', '67');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1009', '1', '7');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1010', '1', '64');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1011', '1', '8');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1012', '1', '9');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1013', '1', '13');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1014', '1', '14');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1015', '1', '15');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1016', '1', '16');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1017', '1', '19');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1018', '1', '27');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1019', '1', '28');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1020', '1', '17');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1021', '1', '21');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1022', '1', '38');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1023', '1', '31');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1024', '1', '33');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1025', '1', '34');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1026', '1', '43');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1027', '1', '44');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1028', '1', '48');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1029', '1', '49');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1030', '1', '51');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1031', '1', '52');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1032', '1', '65');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1033', '1', '54');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1034', '1', '55');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1035', '1', '56');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1036', '1', '58');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1037', '1', '59');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1038', '1', '60');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1039', '1', '63');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1040', '1', '66');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1092', '8', '1');
INSERT INTO `asesores_viejo`.`usu_permisos_menu` VALUES ('1093', '8', '2');
UPDATE `usu_permisos_menu` SET `id_permiso`='859', `id_subrol`='2', `id_menu`='1'  WHERE (`id_permiso` = 859) ;
UPDATE `usu_permisos_menu` SET `id_permiso`='861', `id_subrol`='2', `id_menu`='7'  WHERE (`id_permiso` = 861) ;
UPDATE `usu_permisos_menu` SET `id_permiso`='862', `id_subrol`='2', `id_menu`='64'  WHERE (`id_permiso` = 862) ;
UPDATE `usu_permisos_menu` SET `id_permiso`='863', `id_subrol`='2', `id_menu`='8'  WHERE (`id_permiso` = 863) ;
UPDATE `usu_permisos_menu` SET `id_permiso`='864', `id_subrol`='2', `id_menu`='9'  WHERE (`id_permiso` = 864) ;
UPDATE `usu_permisos_menu` SET `id_permiso`='865', `id_subrol`='2', `id_menu`='40'  WHERE (`id_permiso` = 865) ;
UPDATE `usu_permisos_menu` SET `id_permiso`='866', `id_subrol`='2', `id_menu`='45'  WHERE (`id_permiso` = 866) ;
UPDATE `usu_permisos_menu` SET `id_permiso`='867', `id_subrol`='2', `id_menu`='60'  WHERE (`id_permiso` = 867) ;
UPDATE `usu_permisos_menu` SET `id_permiso`='860', `id_subrol`='2', `id_menu`='6'  WHERE (`id_permiso` = 860) ;
	/*End   of batch : 1 */

COMMIT;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
